concurrency: release-${{ github.ref }}
jobs:
  jpackage:
    name: Run JPackage
    uses: ./.github/workflows/jpackage.yml
  release:
    name: Draft release
    needs: jpackage
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Get qupath version from gradle
      run: "# grep reads the version line, sed strips everything before =\n# GITHUB_ENV\
        \ means it's stored in env.QUPATH_VERSION persistently\n# not just for the\
        \ current step...                \necho \"QUPATH_VERSION=$(grep 'qupathVersion\
        \ = \\\".*\\\"' settings.gradle  | sed -e 's/.*= \"\\(.*\\)\"/\\1/')\" >>\
        \ $GITHUB_ENV\n"
      shell: bash
    - continue-on-error: true
      uses: actions/download-artifact@v4
      with:
        merge-multiple: true
        pattern: QuPath*
    - continue-on-error: true
      name: Wrangle files
      run: 'mv QuPath-${{ env.QUPATH_VERSION }}.msi QuPath-v${{ env.QUPATH_VERSION
        }}-Windows.msi

        mv QuPath-${{ env.QUPATH_VERSION }}.zip QuPath-v${{ env.QUPATH_VERSION }}-Windows.zip

        mv QuPath-${{ env.QUPATH_VERSION }}-x64.pkg QuPath-v${{ env.QUPATH_VERSION
        }}-Mac-x64.pkg

        mv QuPath-${{ env.QUPATH_VERSION }}-arm64.pkg QuPath-v${{ env.QUPATH_VERSION
        }}-Mac-arm64.pkg

        '
      shell: bash
    - continue-on-error: true
      env:
        GH_TOKEN: ${{ github.token }}
      name: Release
      run: "gh release create --draft v${{ env.QUPATH_VERSION }} -t ${{ github.sha\
        \ }} --title v${{ env.QUPATH_VERSION }} \\\n    QuPath-v${{ env.QUPATH_VERSION\
        \ }}-Windows.msi \\\n    QuPath-v${{ env.QUPATH_VERSION }}-Windows.zip \\\n\
        \    QuPath-v${{ env.QUPATH_VERSION }}-Mac-x64.pkg \\\n    QuPath-v${{ env.QUPATH_VERSION\
        \ }}-Mac-arm64.pkg \\\n    QuPath-v${{ env.QUPATH_VERSION }}-Linux.tar.xz\n"
name: Draft a GitHub release
on:
  repository_dispatch:
    types: trigger-ga___github-release.yml
permissions:
  contents: write
