jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Get qupath version from gradle
      run: '# grep reads the version line, sed strips everything before =

        # GITHUB_ENV means it''s stored in ${{env.QUPATH_VERSION}} persistently

        # not just for the current step...

        echo "QUPATH_VERSION=$(grep ''qupathVersion = \".*\"'' settings.gradle  |
        sed -e ''s/.*= \"\(.*\)\"/\1/'')" >> $GITHUB_ENV

        '
      shell: bash
    - continue-on-error: true
      name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '21'
    - continue-on-error: true
      name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v2
    - continue-on-error: true
      name: Build with Gradle
      uses: gradle/gradle-build-action@v3
      with:
        arguments: jpackage -P git-commit=true -P package=installer mergedJavadoc
          createChecksums -P toolchain=21
    - continue-on-error: true
      if: matrix.name == 'Linux'
      name: Make Linux tar.xz
      run: 'tar -c build/dist/QuPath/ | xz > build/dist/QuPath-v${{ env.QUPATH_VERSION
        }}-${{ matrix.name }}.tar.xz

        rm -r build/dist/QuPath/

        '
      shell: bash
    - continue-on-error: true
      if: matrix.name == 'Windows'
      name: Clean windows artifact
      run: 'rm -r build/dist/QuPath-${{ env.QUPATH_VERSION }}

        '
      shell: bash
    - continue-on-error: true
      uses: actions/upload-artifact@v4
      with:
        name: QuPath-v${{ env.QUPATH_VERSION }}-${{ matrix.name }}
        path: build/dist/QuPath*
        retention-days: 1
    - continue-on-error: true
      if: matrix.name == 'Mac-arm64'
      uses: actions/upload-artifact@v4
      with:
        name: javadoc-QuPath-v${{ env.QUPATH_VERSION }}
        path: build/docs-merged/javadoc
        retention-days: 7
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: Linux
          platform: ubuntu-latest
        - name: Mac-x64
          platform: macos-12
        - name: Mac-arm64
          platform: macos-14
        - name: Windows
          platform: windows-latest
name: Build packages with jpackage
on:
  repository_dispatch:
    types: trigger-ga___jpackage.yml
